import 'features/catalog/domain/product.dart';

final List<Product> fakeProducts = [
  Product(
    id: '1',
    productNumber: 'EL-001',
    name: 'Rolex Submariner',
    segment: 'ساعات',
    category: 'watches',
    brand: 'Rolex',
    price: 9500,
    image: 'https://via.placeholder.com/300',
    description: 'Luxury Swiss watch',
    sellerName: 'Elite Store',
    sellerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
  ),
  Product(
    id: '2',
    productNumber: 'EL-002',
    name: 'Omega Seamaster',
    segment: 'ساعات',
    category: 'watches',
    brand: 'Omega',
    price: 6200,
    image: 'https://via.placeholder.com/300',
    description: 'Professional diver watch',
    sellerName: 'Elite Store',
    sellerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
  ),
  Product(
    id: '3',
    productNumber: 'EL-003',
    name: 'Dior Sauvage',
    segment: 'عطور',
    category: 'perfumes',
    brand: 'Dior',
    price: 130,
    image: 'https://via.placeholder.com/300',
    description: 'Luxury fragrance',
    sellerName: 'Elite Store',
    sellerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
  ),
  Product(
    id: '4',
    productNumber: 'EL-004',
    name: 'Gucci Sunglasses',
    segment: 'نظارات',
    category: 'glasses',
    brand: 'Gucci',
    price: 220,
    image: 'https://via.placeholder.com/300',
    description: 'Premium sunglasses',
    sellerName: 'Elite Store',
    sellerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
  ),
  Product(
    id: '5',
    productNumber: 'EL-005',
    name: 'Nike Air Jordan',
    segment: 'شوزات',
    category: 'shoes',
    brand: 'Nike',
    price: 210,
    image: 'https://via.placeholder.com/300',
    description: 'Luxury sneakers',
    sellerName: 'Elite Store',
    sellerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
  ),

];