import 'models/product.dart';

final List<Product> fakeProducts = [
  Product(
    id: 'fake-1',
    productNumber: 'EL-001',
    name: 'Rolex Submariner',
    segment: kMenSegment,
    category: 'watches',
    brand: 'Rolex',
    price: 9500,
    imageUrl: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=900&q=80',
    description: 'Luxury Swiss watch',
    ownerName: 'Elite Store',
    ownerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
    createdAt: DateTime(2026, 1, 1),
  ),
  Product(
    id: 'fake-2',
    productNumber: 'EL-002',
    name: 'Omega Seamaster',
    segment: kMenSegment,
    category: 'watches',
    brand: 'Omega',
    price: 6200,
    imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80',
    description: 'Professional diver watch',
    ownerName: 'Elite Store',
    ownerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
    createdAt: DateTime(2026, 1, 2),
  ),
  Product(
    id: 'fake-3',
    productNumber: 'EL-003',
    name: 'Office Code Bag',
    segment: kWomenSegment,
    category: 'handbags',
    brand: 'Dior',
    price: 234,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',
    description: 'Structured premium bag with elegant daily silhouette.',
    ownerName: 'Elite Store',
    ownerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
    createdAt: DateTime(2026, 1, 3),
  ),
  Product(
    id: 'fake-4',
    productNumber: 'EL-004',
    name: 'Belt Bag',
    segment: kWomenSegment,
    category: 'handbags',
    brand: 'Gucci',
    price: 234,
    imageUrl: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80',
    description: 'Soft golden-tone bag inspired by modern city styling.',
    ownerName: 'Elite Store',
    ownerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
    createdAt: DateTime(2026, 1, 4),
  ),
  Product(
    id: 'fake-5',
    productNumber: 'EL-005',
    name: 'Old Fashion Bag',
    segment: kAntiqueSegment,
    category: 'vintage',
    brand: 'Elite Heritage',
    price: 234,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    description: 'Vintage-inspired collectible piece with bold character.',
    ownerName: 'Elite Store',
    ownerPhone: '0790000000',
    stock: 1,
    isFeatured: true,
    createdAt: DateTime(2026, 1, 5),
  ),
];
