// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPrEGOGGfQm3oFsKCCLbqUSLZJEKHz7U',
    appId: '1:250172830175:web:62fdaecd17a5615a8dd46a',
    messagingSenderId: '250172830175',
    projectId: 'elite-76b99',
    authDomain: 'elite-76b99.firebaseapp.com',
    storageBucket: 'elite-76b99.firebasestorage.app',
    measurementId: 'G-6PFDJRYM0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzcjuB59-GZ13QxSyY0QyZsExHGVdBUE',
    appId: '1:250172830175:android:d375641b95ca22578dd46a',
    messagingSenderId: '250172830175',
    projectId: 'elite-76b99',
    storageBucket: 'elite-76b99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tb-IcOeP_P7mTjPCIgQFZLXGCoGXVLA',
    appId: '1:250172830175:ios:26be3655d46eac5b8dd46a',
    messagingSenderId: '250172830175',
    projectId: 'elite-76b99',
    storageBucket: 'elite-76b99.firebasestorage.app',
    iosBundleId: 'com.example.elite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPrEGOGGfQm3oFsKCCLbqUSLZJEKHz7U',
    appId: '1:250172830175:web:bf81b3c8852b49468dd46a',
    messagingSenderId: '250172830175',
    projectId: 'elite-76b99',
    authDomain: 'elite-76b99.firebaseapp.com',
    storageBucket: 'elite-76b99.firebasestorage.app',
    measurementId: 'G-JP899N3DJY',
  );
}
